### ISSUE TITLE
Incompatible with RedCraft Addons

### ISSUE THREAD

**Issue by boasbakker** [RubixDev/fabric-rug#23] opened 2021-06-23 13:44 UTC
If you use this mod on a server the server crashed
```
[15:40:39] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at com.rubixdev.rug.RugServer.copyRecipes(RugServer.java:242) ~[fabric-rug-1.17-1.1.9.jar:?]
	at com.rubixdev.rug.RugServer.updateCraftingRule(RugServer.java:220) ~[fabric-rug-1.17-1.1.9.jar:?]
	at com.rubixdev.rug.RugServer.registerCraftingRule(RugServer.java:160) ~[fabric-rug-1.17-1.1.9.jar:?]
	at com.rubixdev.rug.RugServer.onServerLoadedWorlds(RugServer.java:146) ~[fabric-rug-1.17-1.1.9.jar:?]
	at carpet.CarpetServer.lambda$onServerLoadedWorlds$1(CarpetServer.java:111) ~[carpet-1.17-1.4.40+v210608.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:111) ~[carpet-1.17-1.4.40+v210608.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bpa000$serverLoadedWorlds(MinecraftServer.java:7799) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:358) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:183) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
My client also crashed when using this mod in 1.17, but that is maybe because incompatibility with an other mod

**Comment by RubixDev** [comment] 2021-06-26 16:05
I cannot reproduce this issue using a fresh fabric server with:
- `fabric-installer-0.7.4.jar`
- Java 16
- `fabric-api-0.36.0+1.17.jar`
- `fabric-carpet-1.17-1.4.40+v210608.jar`
- `fabric-rug-1.17-1.1.9.jar`

For some reason java doesn't find the custom crafting recipes inside the jar file. Would you be able to sent the whole crash report or log file and a list of the other mods you use?

**Comment by boasbakker** [comment] 2021-06-26 20:12
Hmmmh weird, seems to be fixed now. I also can't reproduce it

**Comment by RubixDev** [comment] 2021-06-26 21:08
Maybe the mod jar was partially corrupted or something. I will close this now.

**Comment by Fiznik** [comment] 2021-06-29 18:32
Had this same exact issue whilst trying to launch with both rug and Carpet RedCraft Addons. Removing RedCraft fixed it so there may be an incompatibility there atleast. Hope this fixes your issue aswell

**Comment by RubixDev** [comment] 2021-06-30 07:20
Ok, that would make sense, as they have custom recipes as well. I am going to investigate this as soon as possible.

**Comment by RubixDev** [comment] 2021-07-05 18:08
Well that is funny. I started a new world with my friend a few days ago with a bunch of carpet and rug features enabled and noticed the `unpackableX` rules were not working anymore. Today I looked into that and got it fixed and at the same time cleaned that code up (see 64dbf56f341be4ea17b6de7d1187910659065c81).

Afterwards I now wanted to tackle this issue, but after adding the [RedCraft Addons](https://github.com/MultiCoreNetwork/carpet-redcraft-addons) to my development environment there was no issue with starting. However, there was when using the latest release of Rug instead of the latest unreleased code. So I seem to have fixed this issue on accident while fixing another issue...

**Comment by xDraxxis** [comment] 2021-07-09 01:54
I still get this crash with these. 
[crash-2021-07-09_03.53.25-server.txt](https://github.com/RubixDev/Rug/files/6788172/crash-2021-07-09_03.53.25-server.txt)


- Carpet-RedcraftAddons-1.17-1.4.40
- Fabric-Api-0.36.1+1.17
- Fabric-Carpet-1.17.1-1.4.43+v210706
- Rug-1.17.1-1.1.10

**Comment by RubixDev** [comment] 2021-07-09 09:51
I sadly can confirm this. Idk why it didn't happen when testing last time.

**Comment by RubixDev** [comment] 2021-07-09 10:33
Ehem... I just realized we both have a `craftableCobwebs` rule. I think I will ask them to disable their rule while Rug is installed too, as in my implementation one can choose between two different recipes, whereas with theirs it's only one of them. Until then I now just catch the error and let their rule the priority. A release with that and hopefully another bugfix ( #25 ) will probably come today

**Comment by RubixDev** [comment] 2021-07-09 16:47
That release is now out, but I'll still let this open, as it's not really fixed yet

**Closed as completed** 2021-07-15 07:54 UTC
Labels: incompatibilty
