### ISSUE TITLE
Incompatibility with Reach Entity Attributes

### ISSUE THREAD

**Issue by Neubulae** [RubixDev/fabric-rug#13] opened 2021-03-10 19:06 UTC
three individual crash reports all in one go:
[crash-2021-03-11_03.00.19-server.txt](https://github.com/RubixDev/fabric-rug/files/6118268/crash-2021-03-11_03.00.19-server.txt)
[crash-2021-03-11_03.00.23-server.txt](https://github.com/RubixDev/fabric-rug/files/6118269/crash-2021-03-11_03.00.23-server.txt)
[crash-2021-03-11_03.00.24-client.txt](https://github.com/RubixDev/fabric-rug/files/6118270/crash-2021-03-11_03.00.24-client.txt)

**Comment by RubixDev** [comment] 2021-03-10 19:27
Seems to be an incompatibilty with [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes). Did it work without crashing since your last crash report once? I haven't touched `reachDistance` since then.
I hope it'll be enough if I just lower the priority of my mixin, as it's pretty much redundant with that mod installed.

**Comment by RubixDev** [comment] 2021-03-10 19:50
Also have you already tried updating reach-entity-attributes? I saw you use v1.0.2 but at least [v2.0.0](https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/reach-entity-attributes/) is out already

**Comment by RubixDev** [comment] 2021-03-10 20:14
Can you try if [this](https://rubixdev.tk/files/minecraft/fabric-rug-1.16.5-1.1.6-beta.1.jar) works?

**Comment by Neubulae** [comment] 2021-03-11 09:09
> Seems to be an incompatibilty with [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes). Did it work without crashing since your last crash report once? I haven't touched `reachDistance` since then.
> I hope it'll be enough if I just lower the priority of my mixin, as it's pretty much redundant with that mod installed.

no, last report immediately followed by this

**Comment by RubixDev** [comment] 2021-03-11 10:38
> Can you try if [this](https://rubixdev.tk/files/minecraft/fabric-rug-1.16.5-1.1.6-beta.1.jar) works?

Have you tried that? I can't really test it myself atm

**Comment by Neubulae** [comment] 2021-03-12 07:02
[crash-2021-03-12_15.00.45-server.txt](https://github.com/RubixDev/fabric-rug/files/6128153/crash-2021-03-12_15.00.45-server.txt)
[crash-2021-03-12_15.00.49-server.txt](https://github.com/RubixDev/fabric-rug/files/6128155/crash-2021-03-12_15.00.49-server.txt)
[crash-2021-03-12_15.00.50-client.txt](https://github.com/RubixDev/fabric-rug/files/6128156/crash-2021-03-12_15.00.50-client.txt)
Seems like the crash report is still the same

**Comment by RubixDev** [comment] 2021-03-12 11:35
Next try: [This](https://rubixdev.tk/files/minecraft/fabric-rug-1.16.5-1.1.6-beta.2.jar) should in theory work, at least it did in my tests with reach-entity-attributes v1.0.1, I would just like a confirmation before I close the issue.
I now fully disable the conflicting mixins of my mod while reach-entity-attributes is installed.

**Comment by Neubulae** [comment] 2021-03-12 12:00
confirmed working(at least the client booted up). One thing notable is that REA 2.0 is only available for 1.17. thnakx a lot

**Comment by Mattabase** [comment] 2022-06-29 20:35
Still an issue in 1.19

**Comment by Mattabase** [comment] 2022-06-29 20:43
Happy to grab a log if need be, you can reproduce it by installing origins which uses REA causing a conflict with RUG

**Comment by RubixDev** [comment] 2022-06-30 07:53
I think, I already know the cause, but since I am on vacation now I will have to find a better wifi connection somewhere before I can work on it

**Closed as completed** 2022-07-01 19:11 UTC
Labels: incompatibilty

**Comment by RubixDev** [comment] 2022-07-01 19:24
@Mattabase can you please try [this pre-release](https://github.com/RubixDev/Rug/releases/tag/v1.3.4-beta.1)? When it works I can make it stable

**Comment by Mattabase** [comment] 2022-07-01 19:49
> 

Quick test and looks to have stopped the crash but the reach rule in Rug seems to not be applying 

Doing more testing with a smaller instance, this was being done in my large test instance.

**Comment by Mattabase** [comment] 2022-07-01 19:58
![image](https://user-images.githubusercontent.com/2126947/176961156-13b6230b-dfdf-47b9-b226-a60e3ad87e05.png)
Same issue in a smaller pack, no more crash however reach rule does not apply

**Comment by RubixDev** [comment] 2022-07-01 20:08
That is to be expected. When you have a look at the [README](https://github.com/RubixDev/Rug#reachdistance) it says `reachDistance` is disabled when REA is installed, because they both try to change the same vanilla constants. It should be possible to use another mod based on REA to instead change the player's range though (like [Reach Out](https://www.curseforge.com/minecraft/mc-mods/reach-out) maybe).

**Comment by Mattabase** [comment] 2022-07-01 20:13
Cool thanks for the crash fix
